
 
export const EmployerConstants={

    GET_ALL_EMPLOYER_REQUEST:'GET_ALL_EMPLOYER_REQUEST',
    GET_ALL_EMPLOYER_SUCCESS:'GET_ALL_EMPLOYER_SUCCESS',
    GET_ALL_EMPLOYER_FAILURE:'GET_ALL_EMPLOYER_FAILURE',
    
    ADD_EMPLOYER_REQUEST :'ADD_EMPLOYER_REQUEST',
    ADD_EMPLOYER_SUCCESS :'ADD_EMPLOYER_SUCCESS',
    ADD_EMPLOYER_FAILURE :'ADD_EMPLOYER_FAILURE',
    
    DELETE_EMPLOYER_REQUEST :'DELETE_EMPLOYER_REQUEST',
    DELETE_EMPLOYER_SUCCESS :'DELETE_EMPLOYER_SUCCESS',
    DELETE_EMPLOYER_FAILURE :'DELETE_EMPLOYER_FAILURE',
    
    EDIT_EMPLOYER_REQUEST :'EDIT_EMPLOYER_REQUEST',
    EDIT_EMPLOYER_SUCCESS :'EDIT_EMPLOYER_SUCCESS',
    EDIT_EMPLOYER_FAILURE :'EDIT_EMPLOYER_FAILURE',
    
     }
     export const DepartementConstants={

        GET_ALL_DEPARTEMENT_REQUEST:'GET_ALL_DEPARTEMENT_REQUEST',
        GET_ALL_DEPARTEMENT_SUCCESS:'GET_ALL_DEPARTEMENT_SUCCESS',
        GET_ALL_DEPARTEMENT_FAILURE:'GET_ALL_DEPARTEMENT_FAILURE',
        
        ADD_DEPARTEMENT_REQUEST :'ADD_DEPARTEMENT_REQUEST',
        ADD_DEPARTEMENT_SUCCESS :'ADD_DEPARTEMENT_SUCCESS',
        ADD_DEPARTEMENT_FAILURE :'ADD_DEPARTEMENT_FAILURE',
        
        DELETE_DEPARTEMENT_REQUEST :'DELETE_DEPARTEMENT_REQUEST',
        DELETE_DEPARTEMENT_SUCCESS :'DELETE_DEPARTEMENT_SUCCESS',
        DELETE_DEPARTEMENT_FAILURE :'DELETE_DEPARTEMENT_FAILURE',
        
        EDIT_DEPARTEMENT_REQUEST :'EDIT_DEPARTEMENT_REQUEST',
        EDIT_DEPARTEMENT_SUCCESS :'EDIT_DEPARTEMENT_SUCCESS',
        EDIT_DEPARTEMENT_FAILURE :'EDIT_DEPARTEMENT_FAILURE',
        
         }


     export const TacheConstants={

            GET_ALL_TASKS_REQUEST:'GET_ALL_TASKS_REQUEST',
            GET_ALL_TASKS_SUCCESS:'GET_ALL_TASKS_SUCCESS',
            GET_ALL_TASKS_FAILURE:'GET_ALL_TASKS_FAILURE',
            
            ADD_TASKS_REQUEST :'ADD_TASKS_REQUEST',
            ADD_TASKS_SUCCESS :'ADD_TASKS_SUCCESS',
            ADD_TASKS_FAILURE :'ADD_TASKS_FAILURE',
            
            DELETE_TASKS_REQUEST :'DELETE_TASKS_REQUEST',
            DELETE_TASKS_SUCCESS :'DELETE_TASKS_SUCCESS',
            DELETE_TASKS_FAILURE :'DELETE_TASKS_FAILURE',
            
            EDIT_TASKS_REQUEST :'EDIT_TASKS_REQUEST',
            EDIT_TASKS_SUCCESS :'EDIT_TASKS_SUCCESS',
            EDIT_TASKS_FAILURE :'EDIT_TASKS_FAILURE',
            
             }

             export const recalamationConstants={

              GET_ALL_RECLAMATION_REQUEST:'GET_ALL_RECLAMATION_REQUEST',
              GET_ALL_RECLAMATION_SUCCESS:'GET_ALL_RECLAMATION_SUCCESS',
              GET_ALL_RECLAMATION_FAILURE:'GET_ALL_RECLAMATION_FAILURE',
              
              ADD_RECLAMATION_REQUEST :'ADD_RECLAMATION_REQUEST',
              ADD_RECLAMATION_SUCCESS :'ADD_RECLAMATION_SUCCESS',
              ADD_RECLAMATION_FAILURE :'ADD_RECLAMATION_FAILURE',
              
              DELETE_RECLAMATION_REQUEST :'DELETE_RECLAMATION_REQUEST',
              DELETE_RECLAMATION_SUCCESS :'DELETE_RECLAMATION_SUCCESS',
              DELETE_RECLAMATION_FAILURE :'DELETE_RECLAMATION_FAILURE',
              
              EDIT_RECLAMATION_REQUEST :'EDIT_RECLAMATION_REQUEST',
              EDIT_RECLAMATION_SUCCESS :'EDIT_RECLAMATION_SUCCESS',
              EDIT_RECLAMATION_FAILURE :'EDIT_RECLAMATION_FAILURE',
              
               }
  
  
             
     export const ProjetConstants={

        GET_ALL_PROJET_REQUEST:'GET_ALL_PROJET_REQUEST',
        GET_ALL_PROJET_SUCCESS:'GET_ALL_PROJET_SUCCESS',
        GET_ALL_PROJET_FAILURE:'GET_ALL_PROJET_FAILURE',
        
        ADD_PROJET_REQUEST :'ADD_PROJET_REQUEST',
        ADD_PROJET_SUCCESS :'ADD_PROJET_SUCCESS',
        ADD_PROJET_FAILURE :'ADD_PROJET_FAILURE',
        
        DELETE_PROJET_REQUEST :'DELETE_PROJET_REQUEST',
        DELETE_PROJET_SUCCESS :'DELETE_PROJET_SUCCESS',
        DELETE_PROJET_FAILURE :'DELETE_PROJET_FAILURE',
        
        EDIT_PROJET_REQUEST :'EDIT_PROJET_REQUEST',
        EDIT_PROJET_SUCCESS :'EDIT_PROJET_SUCCESS',
        EDIT_PROJET_FAILURE :'EDIT_PROJET_FAILURE',
        
         }
        
         export const archiveConstants = {
            LISTE_EMPLOYER_ARCHIVE_REQUEST: 'LISTE_EMPLOYER_ARCHIVE_REQUEST',
            LISTE_EMPLOYER_ARCHIVE_SUCCESS: 'LISTE_EMPLOYER_ARCHIVE_SUCCESS',
            LISTE_EMPLOYER_ARCHIVE_FAILURE: 'LISTE_EMPLOYER_ARCHIVE_FAILURE',

            DELETE_EMPLOYER_ARCHIVE_REQUEST: 'DELETE_EMPLOYER_ARCHIVE_REQUEST',
            DELETE_EMPLOYER_ARCHIVE_SUCCESS: 'DELETE_EMPLOYER_ARCHIVE_SUCCESS',
            DELETE_EMPLOYER_ARCHIVE_FAILURE: 'DELETE_EMPLOYER_ARCHIVE_FAILURE',

            AJOUTER_EMPLOYER_ARCHIVE_REQUEST: 'AJOUTER_EMPLOYER_ARCHIVE_REQUEST',
            AJOUTER_EMPLOYER_ARCHIVE_SUCCESS: 'AJOUTER_EMPLOYER_ARCHIVE_SUCCESS',
            AJOUTER_EMPLOYER_ARCHIVE_FAILURE: 'AJOUTER_EMPLOYER_ARCHIVE_FAILURE',
          };

          export const congerConstants={

            GET_ALL_CONGER_REQUEST:'GET_ALL_CONGER_REQUEST',
            GET_ALL_CONGER_SUCCESS:'GET_ALL_CONGER_SUCCESS',
            GET_ALL_CONGER_FAILURE:'GET_ALL_CONGER_FAILURE',
            
            ADD_CONGER_REQUEST :'ADD_CONGER_REQUEST',
            ADD_CONGER_SUCCESS :'ADD_CONGER_SUCCESS',
            ADD_CONGER_FAILURE :'ADD_CONGER_FAILURE',
            
            DELETE_CONGER_REQUEST :'DELETE_CONGER_REQUEST',
            DELETE_CONGER_SUCCESS :'DELETE_CONGER_SUCCESS',
            DELETE_CONGER_FAILURE :'DELETE_CONGER_FAILURE',
            
            EDIT_CONGER_REQUEST :'EDIT_CONGER_REQUEST',
            EDIT_CONGER_SUCCESS :'EDIT_CONGER_SUCCESS',
            EDIT_CONGER_FAILURE :'EDIT_CONGER_FAILURE',
            
             }



             export const reunionConstants={

               GET_ALL_REUNION_REQUEST:'GET_ALL_REUNION_REQUEST',
               GET_ALL_REUNION_SUCCESS:'GET_ALL_REUNION_SUCCESS',
               GET_ALL_REUNION_FAILURE:'GET_ALL_REUNION_FAILURE',
               
               ADD_REUNION_REQUEST :'ADD_REUNION_REQUEST',
               ADD_REUNION_SUCCESS :'ADD_REUNION_SUCCESS',
               ADD_REUNION_FAILURE :'ADD_REUNION_FAILURE',
               
               DELETE_REUNION_REQUEST :'DELETE_REUNION_REQUEST',
               DELETE_REUNION_SUCCESS :'DELETE_REUNION_SUCCESS',
               DELETE_REUNION_FAILURE :'DELETE_REUNION_FAILURE',
               
               EDIT_REUNION_REQUEST :'EDIT_REUNION_REQUEST',
               EDIT_REUNION_SUCCESS :'EDIT_REUNION_SUCCESS',
               EDIT_REUNION_FAILURE :'EDIT_REUNION_FAILURE',
               
                }
            
                export const evenementConstants={

                  GET_ALL_EVENEMENT_REQUEST:'GET_ALL_EVENEMENT_REQUEST',
                  GET_ALL_EVENEMENT_SUCCESS:'GET_ALL_EVENEMENT_SUCCESS',
                  GET_ALL_EVENEMENT_FAILURE:'GET_ALL_EVENEMENT_FAILURE',
                  
                  ADD_EVENEMENT_REQUEST :'ADD_EVENEMENT_REQUEST',
                  ADD_EVENEMENT_SUCCESS :'ADD_EVENEMENT_SUCCESS',
                  ADD_EVENEMENT_FAILURE :'ADD_EVENEMENT_FAILURE',
                  
                  DELETE_EVENEMENT_REQUEST :'DELETE_EVENEMENT_REQUEST',
                  DELETE_EVENEMENT_SUCCESS :'DELETE_EVENEMENT_SUCCESS',
                  DELETE_EVENEMENT_FAILURE :'DELETE_EVENEMENT_FAILURE',
                  
                  EDIT_EVENEMENT_REQUEST :'EDIT_EVENEMENT_REQUEST',
                  EDIT_EVENEMENT_SUCCESS :'EDIT_EVENEMENT_SUCCESS',
                  EDIT_EVENEMENT_FAILURE :'EDIT_EVENEMENT_FAILURE',
                  
                   };



                   export const archiverConstants = {
                    LISTE_RECLAMATION_ARCHIVE_REQUEST: 'LISTE_RECLAMATION_ARCHIVE_REQUEST',
                    LISTE_RECLAMATION_ARCHIVE_SUCCESS: 'LISTE_RECLAMATION_ARCHIVE_SUCCESS',
                    LISTE_RECLAMATION_ARCHIVE_FAILURE: 'LISTE_RECLAMATION_ARCHIVE_FAILURE',
        
                    DELETE_RECLAMATION_ARCHIVE_REQUEST: 'DELETE_RECLAMATION_ARCHIVE_REQUEST',
                    DELETE_RECLAMATION_ARCHIVE_SUCCESS: 'DELETE_RECLAMATION_ARCHIVE_SUCCESS',
                    DELETE_RECLAMATION_ARCHIVE_FAILURE: 'DELETE_RECLAMATION_ARCHIVE_FAILURE',
        
                    AJOUTER_RECLAMATION_ARCHIVE_REQUEST: 'AJOUTER_RECLAMATION_ARCHIVE_REQUEST',
                    AJOUTER_RECLAMATION_ARCHIVE_SUCCESS: 'AJOUTER_RECLAMATION_ARCHIVE_SUCCESS',
                    AJOUTER_RECLAMATION_ARCHIVE_FAILURE: 'AJOUTER_RECLAMATION_ARCHIVE_FAILURE',
                  };

                  export const demandedecompteConstants = {
                    LISTE_COMPTE_REQUEST: 'LISTE_COMPTE_REQUEST',
                    LISTE_COMPTE_SUCCESS: 'LISTE_COMPTE_SUCCESS',
                    LISTE_COMPTE_FAILURE: 'LISTE_COMPTE_FAILURE',
        
                    DELETE_COMPTE_REQUEST: 'DELETE_COMPTE_REQUEST',
                    DELETE_COMPTE_SUCCESS: 'DELETE_COMPTE_SUCCESS',
                    DELETE_COMPTE_FAILURE: 'DELETE_COMPTE_FAILURE',
        
                    AJOUTER_COMPTE_REQUEST: 'AJOUTER_COMPTE_REQUEST',
                    AJOUTER_COMPTE_SUCCESS: 'AJOUTER_COMPTE_SUCCESS',
                    AJOUTER_COMPTE_FAILURE: 'AJOUTER_COMPTE_FAILURE',

                     
                  EDIT_COMPTE_REQUEST :'EDIT_COMPTE_REQUEST',
                  EDIT_COMPTE_SUCCESS :'EDIT_COMPTE_SUCCESS',
                  EDIT_COMPTE_FAILURE :'EDIT_COMPTE_FAILURE',


               SEND_CONFIRMATION_EMAIL_REQUEST :'SEND_CONFIRMATION_EMAIL_REQUEST',
 SEND_CONFIRMATION_EMAIL_SUCCESS :'SEND_CONFIRMATION_EMAIL_SUCCESS',
 SEND_CONFIRMATION_EMAIL_FAILURE :'SEND_CONFIRMATION_EMAIL_FAILURE',

// Constantes pour les actions d'envoi d'e-mail de refus
 SEND_REJECTION_EMAIL_REQUEST :'SEND_REJECTION_EMAIL_REQUEST',
 SEND_REJECTION_EMAIL_SUCCESS :'SEND_REJECTION_EMAIL_SUCCESS',
 SEND_REJECTION_EMAIL_FAILURE :'SEND_REJECTION_EMAIL_FAILURE',
                  };



                  export const congerarchiverConstants = {
                    LISTE_CONGER_ARCHIVE_REQUEST: 'LISTE_CONGER_ARCHIVE_REQUEST',
                    LISTE_CONGER_ARCHIVE_SUCCESS: 'LISTE_CONGER_ARCHIVE_SUCCESS',
                    LISTE_CONGER_ARCHIVE_FAILURE: 'LISTE_CONGER_ARCHIVE_FAILURE',
        
                    DELETE_CONGER_ARCHIVE_REQUEST: 'DELETE_CONGER_ARCHIVE_REQUEST',
                    DELETE_CONGER_ARCHIVE_SUCCESS: 'DELETE_CONGER_ARCHIVE_SUCCESS',
                    DELETE_CONGER_ARCHIVE_FAILURE: 'DELETE_CONGER_ARCHIVE_FAILURE',
        
                    AJOUTER_CONGER_ARCHIVE_REQUEST: 'AJOUTER_CONGER_ARCHIVE_REQUEST',
                    AJOUTER_CONGER_ARCHIVE_SUCCESS: 'AJOUTER_CONGER_ARCHIVE_SUCCESS',
                    AJOUTER_CONGER_ARCHIVE_FAILURE: 'AJOUTER_CONGER_ARCHIVE_FAILURE',
                  };


                  
                  export const demandearchiverConstants = {
                    LISTE_DEMANDE_ARCHIVE_REQUEST: 'LISTE_DEMANDE_ARCHIVE_REQUEST',
                    LISTE_DEMANDE_ARCHIVE_SUCCESS: 'LISTE_DEMANDE_ARCHIVE_SUCCESS',
                    LISTE_DEMANDE_ARCHIVE_FAILURE: 'LISTE_DEMANDE_ARCHIVE_FAILURE',
        
                    DELETE_DEMANDE_ARCHIVE_REQUEST: 'DELETE_DEMANDE_ARCHIVE_REQUEST',
                    DELETE_DEMANDE_ARCHIVE_SUCCESS: 'DELETE_DEMANDE_ARCHIVE_SUCCESS',
                    DELETE_DEMANDE_ARCHIVE_FAILURE: 'DELETE_DEMANDE_ARCHIVE_FAILURE',
        
                    AJOUTER_DEMANDE_ARCHIVE_REQUEST: 'AJOUTER_DEMANDE_ARCHIVE_REQUEST',
                    AJOUTER_DEMANDE_ARCHIVE_SUCCESS: 'AJOUTER_DEMANDE_ARCHIVE_SUCCESS',
                    AJOUTER_DEMANDE_ARCHIVE_FAILURE: 'AJOUTER_DEMANDE_ARCHIVE_FAILURE',
                  };


                  export const cordonneeConstants={

                    GET_ALL_CORDONNEE_REQUEST:'GET_ALL_CORDONNEE_REQUEST',
                    GET_ALL_CORDONNEE_SUCCESS:'GET_ALL_CORDONNEE_SUCCESS',
                    GET_ALL_CORDONNEE_FAILURE:'GET_ALL_CORDONNEE_FAILURE',
                    
                    ADD_CORDONNEE_REQUEST :'ADD_CORDONNEE_REQUEST',
                    ADD_CORDONNEE_SUCCESS :'ADD_CORDONNEE_SUCCESS',
                    ADD_CORDONNEE_FAILURE :'ADD_CORDONNEE_FAILURE',
                    
                    
                    EDIT_CORDONNEE_REQUEST :'EDIT_CORDONNEE_REQUEST',
                    EDIT_CORDONNEE_SUCCESS :'EDIT_CORDONNEE_SUCCESS',
                    EDIT_CORDONNEE_FAILURE :'EDIT_CORDONNEE_FAILURE',
                    
                     }



               
    