
 
export const EmployerConstants={

    GET_ALL_EMPLOYER_REQUEST:'GET_ALL_EMPLOYER_REQUEST',
    GET_ALL_EMPLOYER_SUCCESS:'GET_ALL_EMPLOYER_SUCCESS',
    GET_ALL_EMPLOYER_FAILURE:'GET_ALL_EMPLOYER_FAILURE',
    
    ADD_EMPLOYER_REQUEST :'ADD_EMPLOYER_REQUEST',
    ADD_EMPLOYER_SUCCESS :'ADD_EMPLOYER_SUCCESS',
    ADD_EMPLOYER_FAILURE :'ADD_EMPLOYER_FAILURE',
    
    DELETE_EMPLOYER_REQUEST :'DELETE_EMPLOYER_REQUEST',
    DELETE_EMPLOYER_SUCCESS :'DELETE_EMPLOYER_SUCCESS',
    DELETE_EMPLOYER_FAILURE :'DELETE_EMPLOYER_FAILURE',
    
    EDIT_EMPLOYER_REQUEST :'EDIT_EMPLOYER_REQUEST',
    EDIT_EMPLOYER_SUCCESS :'EDIT_EMPLOYER_SUCCESS',
    EDIT_EMPLOYER_FAILURE :'EDIT_EMPLOYER_FAILURE',
    
     }
     export const DepartementConstants={

        GET_ALL_DEPARTEMENT_REQUEST:'GET_ALL_DEPARTEMENT_REQUEST',
        GET_ALL_DEPARTEMENT_SUCCESS:'GET_ALL_DEPARTEMENT_SUCCESS',
        GET_ALL_DEPARTEMENT_FAILURE:'GET_ALL_DEPARTEMENT_FAILURE',
        
        ADD_DEPARTEMENT_REQUEST :'ADD_DEPARTEMENT_REQUEST',
        ADD_DEPARTEMENT_SUCCESS :'ADD_DEPARTEMENT_SUCCESS',
        ADD_DEPARTEMENT_FAILURE :'ADD_DEPARTEMENT_FAILURE',
        
        DELETE_DEPARTEMENT_REQUEST :'DELETE_DEPARTEMENT_REQUEST',
        DELETE_DEPARTEMENT_SUCCESS :'DELETE_DEPARTEMENT_SUCCESS',
        DELETE_DEPARTEMENT_FAILURE :'DELETE_DEPARTEMENT_FAILURE',
        
        EDIT_DEPARTEMENT_REQUEST :'EDIT_DEPARTEMENT_REQUEST',
        EDIT_DEPARTEMENT_SUCCESS :'EDIT_DEPARTEMENT_SUCCESS',
        EDIT_DEPARTEMENT_FAILURE :'EDIT_DEPARTEMENT_FAILURE',
        
         }


     export const TacheConstants={

            GET_ALL_TASKS_REQUEST:'GET_ALL_TASKS_REQUEST',
            GET_ALL_TASKS_SUCCESS:'GET_ALL_TASKS_SUCCESS',
            GET_ALL_TASKS_FAILURE:'GET_ALL_TASKS_FAILURE',
            
            ADD_TASKS_REQUEST :'ADD_TASKS_REQUEST',
            ADD_TASKS_SUCCESS :'ADD_TASKS_SUCCESS',
            ADD_TASKS_FAILURE :'ADD_TASKS_FAILURE',
            
            DELETE_TASKS_REQUEST :'DELETE_TASKS_REQUEST',
            DELETE_TASKS_SUCCESS :'DELETE_TASKS_SUCCESS',
            DELETE_TASKS_FAILURE :'DELETE_TASKS_FAILURE',
            
            EDIT_TASKS_REQUEST :'EDIT_TASKS_REQUEST',
            EDIT_TASKS_SUCCESS :'EDIT_TASKS_SUCCESS',
            EDIT_TASKS_FAILURE :'EDIT_TASKS_FAILURE',
            
             }


             
     export const ProjetConstants={

        GET_ALL_PROJET_REQUEST:'GET_ALL_PROJET_REQUEST',
        GET_ALL_PROJET_SUCCESS:'GET_ALL_PROJET_SUCCESS',
        GET_ALL_PROJET_FAILURE:'GET_ALL_PROJET_FAILURE',
        
        ADD_PROJET_REQUEST :'ADD_PROJET_REQUEST',
        ADD_PROJET_SUCCESS :'ADD_PROJET_SUCCESS',
        ADD_PROJET_FAILURE :'ADD_PROJET_FAILURE',
        
        DELETE_PROJET_REQUEST :'DELETE_PROJET_REQUEST',
        DELETE_PROJET_SUCCESS :'DELETE_PROJET_SUCCESS',
        DELETE_PROJET_FAILURE :'DELETE_PROJET_FAILURE',
        
        EDIT_PROJET_REQUEST :'EDIT_PROJET_REQUEST',
        EDIT_PROJET_SUCCESS :'EDIT_PROJET_SUCCESS',
        EDIT_PROJET_FAILURE :'EDIT_PROJET_FAILURE',
        
         }
        
    