
 
export const EmployerConstants={

    GET_ALL_EMPLOYER_REQUEST:'GET_ALL_EMPLOYER_REQUEST',
    GET_ALL_EMPLOYER_SUCCESS:'GET_ALL_EMPLOYER_SUCCESS',
    GET_ALL_EMPLOYER_FAILURE:'GET_ALL_EMPLOYER_FAILURE',
    
    ADD_EMPLOYER_REQUEST :'ADD_EMPLOYER_REQUEST',
    ADD_EMPLOYER_SUCCESS :'ADD_EMPLOYER_SUCCESS',
    ADD_EMPLOYER_FAILURE :'ADD_EMPLOYER_FAILURE',
    
    DELETE_EMPLOYER_REQUEST :'DELETE_EMPLOYER_REQUEST',
    DELETE_EMPLOYER_SUCCESS :'DELETE_EMPLOYER_SUCCESS',
    DELETE_EMPLOYER_FAILURE :'DELETE_EMPLOYER_FAILURE',
    
    EDIT_EMPLOYER_REQUEST :'EDIT_EMPLOYER_REQUEST',
    EDIT_EMPLOYER_SUCCESS :'EDIT_EMPLOYER_SUCCESS',
    EDIT_EMPLOYER_FAILURE :'EDIT_EMPLOYER_FAILURE',
    
     }
    